# import tensorflow

In [4]:
import tensorflow as tf

## Tensor dengan Shape(5,5) dengan nilai random yang disimpan dalam variable Random_Tensor.

In [5]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[ 0.59741306, -0.21638517, -0.8104995 ,  0.00557772,  0.6375699 ],
       [-0.7379968 , -0.06377111,  0.13534491, -0.092591  ,  0.13763921],
       [-0.5552957 , -0.82209474,  1.1946009 ,  1.9543308 ,  0.6355978 ],
       [ 0.99732584,  1.33653   ,  0.3635919 ,  0.91267323, -0.584518  ],
       [-0.35073593, -1.9604133 ,  0.6109846 , -1.0721704 ,  0.94315094]],
      dtype=float32)

## Tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable Prime_Tensor.

In [6]:
prime_tensor = tf.convert_to_tensor([[1,3,5,7,11],
                                    [13, 17, 19, 23, 29], 
                                     [31, 37, 41, 43, 47], 
                                    [53, 59, 61, 67, 71], 
                                     [73, 79, 83, 89, 97]], dtype=tf.float32)
print(prime_tensor)

tf.Tensor(
[[ 1.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


## Tampilkan dimensi dari kedua variabel

In [10]:
print("Dimensi Variabel")
print("random_tensor Dimensi :",random_tensor.shape)
print("prime_tensor Dimensi :",prime_tensor.shape)

Dimensi Variabel
random_tensor Dimensi : (5, 5)
prime_tensor Dimensi : (5, 5)


## Hasil perhitungan aritmatika 2 variabel, Gunakan minimal 5 Operator

In [13]:
#Jumlah
a = random_tensor
b = prime_tensor
tf.add(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.5974131,  2.7836149,  4.1895003,  7.0055776, 11.637569 ],
       [12.262003 , 16.93623  , 19.135345 , 22.90741  , 29.13764  ],
       [30.444704 , 36.177906 , 42.1946   , 44.95433  , 47.635597 ],
       [53.997326 , 60.33653  , 61.36359  , 67.912674 , 70.41548  ],
       [72.64926  , 77.03959  , 83.610985 , 87.927826 , 97.94315  ]],
      dtype=float32)>

In [14]:
#pengurangan
tf.subtract(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.40258694,  -3.2163851 ,  -5.8104997 ,  -6.9944224 ,
        -10.362431  ],
       [-13.737997  , -17.06377   , -18.864655  , -23.09259   ,
        -28.86236   ],
       [-31.555296  , -37.822094  , -39.8054    , -41.04567   ,
        -46.364403  ],
       [-52.002674  , -57.66347   , -60.63641   , -66.087326  ,
        -71.58452   ],
       [-73.35074   , -80.96041   , -82.389015  , -90.072174  ,
        -96.05685   ]], dtype=float32)>

In [15]:
#perkalian
tf.multiply(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 5.9741306e-01, -6.4915550e-01, -4.0524974e+00,  3.9044064e-02,
         7.0132689e+00],
       [-9.5939589e+00, -1.0841089e+00,  2.5715532e+00, -2.1295929e+00,
         3.9915371e+00],
       [-1.7214167e+01, -3.0417505e+01,  4.8978638e+01,  8.4036224e+01,
         2.9873098e+01],
       [ 5.2858269e+01,  7.8855270e+01,  2.2179106e+01,  6.1149105e+01,
        -4.1500778e+01],
       [-2.5603724e+01, -1.5487265e+02,  5.0711723e+01, -9.5423164e+01,
         9.1485641e+01]], dtype=float32)>

In [16]:
#pembagian
tf.divide(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.59741306, -0.07212839, -0.1620999 ,  0.00079682,  0.0579609 ],
       [-0.05676899, -0.00375124,  0.00712342, -0.0040257 ,  0.00474618],
       [-0.01791276, -0.02221878,  0.02913661,  0.04544955,  0.01352336],
       [ 0.01881747,  0.02265305,  0.00596052,  0.01362199, -0.00823265],
       [-0.0048046 , -0.02481536,  0.00736126, -0.01204686,  0.00972321]],
      dtype=float32)>

In [17]:
# Pangkat
tf.pow(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 5.97413063e-01, -1.01317037e-02, -3.49754840e-01,
         1.67957290e-16,  7.07629463e-03],
       [-1.92623101e-02, -4.77098471e-21,  3.14337699e-17,
        -1.70247720e-24,  1.05565724e-25],
       [-1.20296715e-08, -7.11392262e-04,  1.46601001e+03,
         3.25774659e+12,  5.61788616e-10],
       [ 8.67690265e-01,  2.70859080e+07,  1.57567580e-27,
         2.19344161e-03, -2.77109228e-17],
       [-6.07517888e-34, -1.24584563e+23,  1.73985592e-18,
        -4.93717529e+02,  3.42276017e-03]], dtype=float32)>

# Nilai maksimum dan minimum dari variabel Random-Tensor

In [25]:
argmax = tf.constant(random_tensor)
print("Nilai Maksimal random_tensor =",tf.argmax(random_tensor,axis=0))
print("Nilai Minimal random_tensor =",tf.argmin(random_tensor,axis=0))

Nilai Maksimal random_tensor = tf.Tensor([3 3 2 2 4], shape=(5,), dtype=int64)
Nilai Minimal random_tensor = tf.Tensor([1 4 0 4 3], shape=(5,), dtype=int64)


## Penggabungan variable Random_Tensor dengan prime_tensor (concatenation)

In [19]:
concat = tf.concat([random_tensor,prime_tensor], axis=0)
concat

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 5.9741306e-01, -2.1638517e-01, -8.1049949e-01,  5.5777235e-03,
         6.3756990e-01],
       [-7.3799682e-01, -6.3771114e-02,  1.3534491e-01, -9.2590995e-02,
         1.3763921e-01],
       [-5.5529571e-01, -8.2209474e-01,  1.1946009e+00,  1.9543308e+00,
         6.3559783e-01],
       [ 9.9732584e-01,  1.3365300e+00,  3.6359191e-01,  9.1267323e-01,
        -5.8451802e-01],
       [-3.5073593e-01, -1.9604133e+00,  6.1098462e-01, -1.0721704e+00,
         9.4315094e-01],
       [ 1.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

## Hasil sorting dari kedua variabel di atas( Descending )

In [21]:
print("Sorting random_tensor Descending")
print(tf.sort(random_tensor,direction="DESCENDING"))
print("\n")
print("Sorting prime_tensor Descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Sorting random_tensor Descending
tf.Tensor(
[[ 0.6375699   0.59741306  0.00557772 -0.21638517 -0.8104995 ]
 [ 0.13763921  0.13534491 -0.06377111 -0.092591   -0.7379968 ]
 [ 1.9543308   1.1946009   0.6355978  -0.5552957  -0.82209474]
 [ 1.33653     0.99732584  0.91267323  0.3635919  -0.584518  ]
 [ 0.94315094  0.6109846  -0.35073593 -1.0721704  -1.9604133 ]], shape=(5, 5), dtype=float32)


Sorting prime_tensor Descending
tf.Tensor(
[[11.  7.  5.  3.  1.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
